import Head from "next/head";
import styles from "@/styles/About.module.scss";
import Layout from "@/components/layout";

import Image from "next/image";
import profileImage from "../../public/ericandido.jpeg";
import gitHubImage from "../../public/github.png";
import linkedinImage from "../../public/linkedin.png";

const About = () => {
  // useEffect(() => {
  //   fetch("/api/posts")
  //     .then((res) => res.json())
  //     .then((data) => console.log(data));
  // }, []);
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../../public/Wild.png" />
      </Head>
      <Layout>
        <h1 className={styles.title}>About me...</h1>
        <div className={styles.Wrapper}>
          <Image
            className={styles.profileImage}
            src={profileImage}
            width={300}
            height={400}
            alt="profileImg"
          />
          <div className={styles.textWrapper}>
            <h3>Erica Candido</h3>
            <p>Ascolto & Creo Applicazioni Web </p>
            <p>Front-end developer </p>
            <h3>Contacts</h3>

            <a href="https://github.com/EricaCandido">
              Github
              <Image src={gitHubImage} width={25} height={25} alt="githubImg" />
            </a>
            <a href="https://www.linkedin.com/in/erica-candido-8085a4259/">
              Linkedin
              <Image
                src={linkedinImage}
                width={25}
                height={25}
                alt="linkedinImg"
              />
            </a>

            <p>Email: ericandido1997@gmail.com</p>
            <h3>Altri progetti</h3>
            <a href="https://movie-plex.vercel.app">MoviePlex</a>
            <a href="https://explorer-project-three.vercel.app">HireLand</a>
            <a href="https://to-do-list-project-phi.vercel.app">DailyTasks</a>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default About;

// export const getServerSideProps = () => {
//   return {
//     props: {
//       data: tableLegendMock,
//     },
//   };
// };
