import Head from "next/head";

import styles from "@/styles/Home.module.scss";

//components
import Layout from "@/components/layout";

// utils

import EventCardList from "@/components/eventCardList";

export default function Event({ data }) {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Layout>
          <EventCardList data={data} />
        </Layout>
      </main>
    </>
  );
}

//richiamare un'api esterna
// export const getServerSideProps = async () => {
//   const res = await fetch(
//     "https://app.ticketmaster.com/discovery/v2/events.json?apikey=AXqJzP261SzkBJzj3TIO9cfbmEg4ygMN"
//   );
//   const data = await res.json();
//   return {
//     props: {
//       data: data._embedded.events,
//     },
//   };
// };

export const getServerSideProps = async () => {
  try {
    const res = await fetch(
      "https://app.ticketmaster.com/discovery/v2/events.json?apikey=AXqJzP261SzkBJzj3TIO9cfbmEg4ygMN"
    );
    const data = await res.json();
    return {
      props: {
        data: data._embedded.events,
      },
    };
  } catch (error) {
    console.error("Errore durante la chiamata API:", error);
    return {
      props: {
        data: [],
      },
    };
  }
};

// export const getStaticProps = () => {
//   const newPostData = getAllNewPosts();

//   return {
//     props: {
//       newPostData,
//     },
//   };
// };
