import Head from "next/head";
import styles from "@/styles/Home.module.scss";

//components
import Layout from "@/components/layout";

// utils
import { postsJson, checkedPost } from "./api/posts";

import CardList from "@/components/cardList";
import Hero from "@/components/hero";

export default function Home({ data }) {
  // useEffect(() => {
  //   fetch("/api/posts")
  //     .then((res) => res.json())
  //     .then((data) => console.log(data));
  // }, []);
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Wild.png" />
      </Head>
      <main className={styles.main}>
        <Layout>
          <Hero />
          <h2 className={styles.title}>In evidenza</h2>
          <CardList data={data} />
        </Layout>
      </main>
    </>
  );
}

//richiamare un'api esterna
// export const getServerSideProps = async () => {
//   const res = await fetch("https://dummyjson.com/products");
//   const data = await res.json();
//   return {
//     props: {
//       data,
//     },
//   };
// };

export const getServerSideProps = () => {
  return {
    props: {
      data: checkedPost(postsJson),
    },
  };
};
